# Generated by Django 5.0.3 on 2024-05-28 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('razboltovka', models.CharField(max_length=120)),
                ('radius', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rims')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.managers')),
                ('rims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.rims')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storages', models.CharField(max_length=120)),
                ('rims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.rims')),
            ],
        ),
    ]
