# Generated by Django 5.0.3 on 2024-06-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='rims',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='rims',
        ),
        migrations.AddField(
            model_name='rims',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manufactor', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='spares')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
