# Generated by Django 5.0.3 on 2024-06-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_remove_sell_manager_remove_sell_rims_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='spares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.spares'),
        ),
    ]
