# Generated by Django 5.0.3 on 2024-06-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cart_spares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rims',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.rims'),
        ),
    ]
